# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\details_session_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DetalisSessionDialog(object):
    def setupUi(self, DetalisSessionDialog):
        DetalisSessionDialog.setObjectName("DetalisSessionDialog")
        DetalisSessionDialog.resize(843, 751)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DetalisSessionDialog.sizePolicy().hasHeightForWidth())
        DetalisSessionDialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(DetalisSessionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.col_edit = QtWidgets.QSpinBox(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.col_edit.sizePolicy().hasHeightForWidth())
        self.col_edit.setSizePolicy(sizePolicy)
        self.col_edit.setMinimum(1)
        self.col_edit.setObjectName("col_edit")
        self.gridLayout.addWidget(self.col_edit, 4, 1, 1, 1)
        self.row_edit = QtWidgets.QSpinBox(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.row_edit.sizePolicy().hasHeightForWidth())
        self.row_edit.setSizePolicy(sizePolicy)
        self.row_edit.setMinimum(1)
        self.row_edit.setObjectName("row_edit")
        self.gridLayout.addWidget(self.row_edit, 3, 1, 1, 1)
        self.name_film_label = QtWidgets.QLabel(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_film_label.sizePolicy().hasHeightForWidth())
        self.name_film_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.name_film_label.setFont(font)
        self.name_film_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_film_label.setObjectName("name_film_label")
        self.gridLayout.addWidget(self.name_film_label, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.img_cont = QtWidgets.QLabel(DetalisSessionDialog)
        self.img_cont.setAlignment(QtCore.Qt.AlignCenter)
        self.img_cont.setObjectName("img_cont")
        self.gridLayout.addWidget(self.img_cont, 2, 0, 1, 3)
        self.buy_ticket_btn = QtWidgets.QPushButton(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_ticket_btn.sizePolicy().hasHeightForWidth())
        self.buy_ticket_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buy_ticket_btn.setFont(font)
        self.buy_ticket_btn.setObjectName("buy_ticket_btn")
        self.gridLayout.addWidget(self.buy_ticket_btn, 3, 2, 2, 1)
        self.date_label = QtWidgets.QLabel(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_label.sizePolicy().hasHeightForWidth())
        self.date_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 1, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(DetalisSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.gridLayout.addWidget(self.time_label, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 10)

        self.retranslateUi(DetalisSessionDialog)
        QtCore.QMetaObject.connectSlotsByName(DetalisSessionDialog)

    def retranslateUi(self, DetalisSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        DetalisSessionDialog.setWindowTitle(_translate("DetalisSessionDialog", "Form"))
        self.label.setText(_translate("DetalisSessionDialog", "Ряд"))
        self.name_film_label.setText(_translate("DetalisSessionDialog", "Name Film"))
        self.label_2.setText(_translate("DetalisSessionDialog", "Место"))
        self.img_cont.setText(_translate("DetalisSessionDialog", "img cont"))
        self.buy_ticket_btn.setText(_translate("DetalisSessionDialog", "Купить билет"))
        self.date_label.setText(_translate("DetalisSessionDialog", "Date"))
        self.time_label.setText(_translate("DetalisSessionDialog", "Time"))

